# PluginManager by Gabry
# If you have problems with this problem, contact me @ Discord: Gabry#6899
# Use 'ยง' to make colored text.

title-prefix: "ยง9[PluginManager]" # Leave it blank if you don't need the prefix.